[package]
name = "teleboxel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
axum = { version = "0.8.8", features = ["ws"] }
fastwebsockets = { version = "0.10.0", features = ["upgrade", "with_axum"] }
bytes = "1.11.0"
